/**/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/diff_drive_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    # Updated wheel joint names based on your URDF
    left_wheel_names: ["rear_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint"]

    # Updated geometry
    wheel_separation: 0.25
    wheel_radius: 0.0325

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint

    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 0.7
    linear.x.min_velocity: -0.7
    linear.x.max_acceleration: 0.7
    linear.x.max_jerk: .nan
    linear.x.min_jerk: .nan

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 8.5
    angular.z.min_velocity: -8.5
    angular.z.max_acceleration: 5.0
    angular.z.min_acceleration: -5.0
    angular.z.max_jerk: .nan
    angular.z.min_jerk: .nan
