twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      nav2_vel:
        topic: /cmd_vel
        timeout: 0.5
        priority: 100
      joystick:
        topic: joy_vel
        timeout: 0.5  # Corrected from 'time_out'
        priority: 90
      keyboard:
        topic: /key_vel
        timeout: 0.5  # Corrected from 'time_out'
        priority: 50